# Seeds for system templates
# Run with: mix run priv/repo/seeds/templates.exs
#
# Idempotent: deletes existing system templates before inserting.

alias QrLabelSystem.Repo
alias QrLabelSystem.Designs.Design
import Ecto.Query

# Clean existing system templates
Repo.delete_all(from d in Design, where: d.template_source == "system")

IO.puts("Deleted existing system templates.")

# Helper to generate unique element IDs
defmodule TemplateHelper do
  def el_id(template_idx, element_idx) do
    "el_tpl_#{template_idx}_#{element_idx}"
  end
end

templates = [
  # =================================================================
  # ALIMENTACIÓN (6 plantillas)
  # =================================================================

  # 1. Producto alimentario básico (100×70mm)
  %{
    name: "Producto alimentario",
    description: "Etiqueta estándar con nombre, peso, EAN-13, lote y caducidad",
    width_mm: 100.0,
    height_mm: 70.0,
    background_color: "#FFFFFF",
    border_width: 0.3,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "alimentacion",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_1_1", type: "text", x: 5.0, y: 5.0, width: 90.0, height: 7.0,
        text_content: nil, binding: "nombre", font_size: 14.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Nombre producto", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_2", type: "line", x: 5.0, y: 14.0, width: 90.0, height: 0.5,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_3", type: "text", x: 5.0, y: 17.0, width: 22.0, height: 5.0,
        text_content: "Peso neto:", binding: nil, font_size: 9.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label peso", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_4", type: "text", x: 28.0, y: 17.0, width: 25.0, height: 5.0,
        text_content: nil, binding: "peso_neto", font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Peso neto", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_5", type: "text", x: 5.0, y: 24.0, width: 12.0, height: 5.0,
        text_content: "Lote:", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_6", type: "text", x: 18.0, y: 24.0, width: 25.0, height: 5.0,
        text_content: nil, binding: "lote", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_7", type: "text", x: 50.0, y: 24.0, width: 12.0, height: 5.0,
        text_content: "Cad.:", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label caducidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_8", type: "text", x: 63.0, y: 24.0, width: 32.0, height: 5.0,
        text_content: nil, binding: "fecha_caducidad", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Fecha caducidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_1_9", type: "barcode", x: 15.0, y: 34.0, width: 70.0, height: 28.0,
        binding: "ean13", barcode_format: "EAN13", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "EAN-13", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 2. Etiqueta nutricional (80×120mm)
  %{
    name: "Información nutricional",
    description: "Tabla de valores nutricionales conforme a normativa UE",
    width_mm: 80.0,
    height_mm: 120.0,
    background_color: "#FFFFFF",
    border_width: 0.3,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "alimentacion",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_2_1", type: "text", x: 4.0, y: 4.0, width: 72.0, height: 6.0,
        text_content: "INFORMACIÓN NUTRICIONAL", binding: nil, font_size: 11.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_2", type: "line", x: 4.0, y: 11.0, width: 72.0, height: 0.5,
        color: "#000000", z_index: 5, name: "Separador 1", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_3", type: "text", x: 4.0, y: 13.0, width: 72.0, height: 5.0,
        text_content: "Valores medios por 100g", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#333333",
        z_index: 10, name: "Subtítulo", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_4", type: "line", x: 4.0, y: 19.0, width: 72.0, height: 0.3,
        color: "#CCCCCC", z_index: 5, name: "Separador 2", visible: true, locked: false, rotation: 0.0},
      # Valor energético
      %{id: "el_tpl_2_5", type: "text", x: 4.0, y: 21.0, width: 45.0, height: 5.0,
        text_content: "Valor energético", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label energía", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_6", type: "text", x: 50.0, y: 21.0, width: 26.0, height: 5.0,
        text_content: nil, binding: "energia_kcal", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "right", color: "#000000",
        z_index: 10, name: "Energía kcal", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_7", type: "line", x: 4.0, y: 27.0, width: 72.0, height: 0.2,
        color: "#EEEEEE", z_index: 4, name: "Línea", visible: true, locked: false, rotation: 0.0},
      # Grasas
      %{id: "el_tpl_2_8", type: "text", x: 4.0, y: 29.0, width: 45.0, height: 5.0,
        text_content: "Grasas", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label grasas", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_9", type: "text", x: 50.0, y: 29.0, width: 26.0, height: 5.0,
        text_content: nil, binding: "grasas", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "right", color: "#000000",
        z_index: 10, name: "Grasas", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_10", type: "text", x: 8.0, y: 35.0, width: 41.0, height: 5.0,
        text_content: "de las cuales saturadas", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label saturadas", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_11", type: "text", x: 50.0, y: 35.0, width: 26.0, height: 5.0,
        text_content: nil, binding: "grasas_saturadas", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "right", color: "#555555",
        z_index: 10, name: "Saturadas", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_12", type: "line", x: 4.0, y: 41.0, width: 72.0, height: 0.2,
        color: "#EEEEEE", z_index: 4, name: "Línea", visible: true, locked: false, rotation: 0.0},
      # Hidratos
      %{id: "el_tpl_2_13", type: "text", x: 4.0, y: 43.0, width: 45.0, height: 5.0,
        text_content: "Hidratos de carbono", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label hidratos", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_14", type: "text", x: 50.0, y: 43.0, width: 26.0, height: 5.0,
        text_content: nil, binding: "hidratos", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "right", color: "#000000",
        z_index: 10, name: "Hidratos", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_15", type: "text", x: 8.0, y: 49.0, width: 41.0, height: 5.0,
        text_content: "de los cuales azúcares", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label azúcares", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_16", type: "text", x: 50.0, y: 49.0, width: 26.0, height: 5.0,
        text_content: nil, binding: "azucares", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "right", color: "#555555",
        z_index: 10, name: "Azúcares", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_17", type: "line", x: 4.0, y: 55.0, width: 72.0, height: 0.2,
        color: "#EEEEEE", z_index: 4, name: "Línea", visible: true, locked: false, rotation: 0.0},
      # Proteínas
      %{id: "el_tpl_2_18", type: "text", x: 4.0, y: 57.0, width: 45.0, height: 5.0,
        text_content: "Proteínas", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label proteínas", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_19", type: "text", x: 50.0, y: 57.0, width: 26.0, height: 5.0,
        text_content: nil, binding: "proteinas", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "right", color: "#000000",
        z_index: 10, name: "Proteínas", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_20", type: "line", x: 4.0, y: 63.0, width: 72.0, height: 0.2,
        color: "#EEEEEE", z_index: 4, name: "Línea", visible: true, locked: false, rotation: 0.0},
      # Sal
      %{id: "el_tpl_2_21", type: "text", x: 4.0, y: 65.0, width: 45.0, height: 5.0,
        text_content: "Sal", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label sal", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_22", type: "text", x: 50.0, y: 65.0, width: 26.0, height: 5.0,
        text_content: nil, binding: "sal", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "right", color: "#000000",
        z_index: 10, name: "Sal", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_23", type: "line", x: 4.0, y: 72.0, width: 72.0, height: 0.5,
        color: "#000000", z_index: 5, name: "Separador final", visible: true, locked: false, rotation: 0.0},
      # Alérgenos
      %{id: "el_tpl_2_24", type: "text", x: 4.0, y: 75.0, width: 72.0, height: 5.0,
        text_content: "ALÉRGENOS:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label alérgenos", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_25", type: "text", x: 4.0, y: 81.0, width: 72.0, height: 12.0,
        text_content: nil, binding: "alergenos", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Alérgenos", visible: true, locked: false, rotation: 0.0},
      # Ingredientes
      %{id: "el_tpl_2_26", type: "text", x: 4.0, y: 95.0, width: 72.0, height: 5.0,
        text_content: "Ingredientes:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#333333",
        z_index: 10, name: "Label ingredientes", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_2_27", type: "text", x: 4.0, y: 101.0, width: 72.0, height: 15.0,
        text_content: nil, binding: "ingredientes", font_size: 6.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#333333",
        z_index: 10, name: "Ingredientes", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 3. Lote/Caducidad compacta (50×30mm)
  %{
    name: "Lote y caducidad",
    description: "Etiqueta compacta de lote y fecha de caducidad",
    width_mm: 50.0,
    height_mm: 30.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "alimentacion",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_3_1", type: "text", x: 2.0, y: 2.0, width: 10.0, height: 4.0,
        text_content: "Lote:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_3_2", type: "text", x: 13.0, y: 2.0, width: 35.0, height: 4.0,
        text_content: nil, binding: "lote", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_3_3", type: "text", x: 2.0, y: 7.0, width: 22.0, height: 4.0,
        text_content: "Consumir antes de:", binding: nil, font_size: 6.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label caducidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_3_4", type: "text", x: 25.0, y: 7.0, width: 23.0, height: 4.0,
        text_content: nil, binding: "fecha_caducidad", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Fecha caducidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_3_5", type: "barcode", x: 3.0, y: 13.0, width: 44.0, height: 14.0,
        binding: "lote", barcode_format: "CODE128", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "Código de barras", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 4. Etiqueta de origen (60×40mm)
  %{
    name: "Origen del producto",
    description: "Etiqueta de trazabilidad con país, región y QR",
    width_mm: 60.0,
    height_mm: 40.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "alimentacion",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_4_1", type: "text", x: 3.0, y: 2.0, width: 34.0, height: 5.0,
        text_content: "ORIGEN", binding: nil, font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_2", type: "line", x: 3.0, y: 8.0, width: 34.0, height: 0.3,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_3", type: "text", x: 3.0, y: 11.0, width: 10.0, height: 4.0,
        text_content: "País:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label país", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_4", type: "text", x: 14.0, y: 11.0, width: 23.0, height: 4.0,
        text_content: nil, binding: "pais", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "País", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_5", type: "text", x: 3.0, y: 17.0, width: 14.0, height: 4.0,
        text_content: "Región:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label región", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_6", type: "text", x: 18.0, y: 17.0, width: 19.0, height: 4.0,
        text_content: nil, binding: "region", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Región", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_7", type: "text", x: 3.0, y: 23.0, width: 18.0, height: 4.0,
        text_content: "Productor:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label productor", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_8", type: "text", x: 22.0, y: 23.0, width: 15.0, height: 4.0,
        text_content: nil, binding: "productor", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Productor", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_9", type: "qr", x: 40.0, y: 8.0, width: 17.0, height: 17.0,
        binding: "url_trazabilidad", qr_error_level: "M", color: "#000000",
        z_index: 8, name: "QR Trazabilidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_4_10", type: "text", x: 40.0, y: 26.0, width: 17.0, height: 4.0,
        text_content: "Escanear", binding: nil, font_size: 5.0, font_weight: "normal",
        font_family: "Arial", text_align: "center", color: "#888888",
        z_index: 10, name: "Label QR", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 5. Alérgenos (70×50mm)
  %{
    name: "Alérgenos",
    description: "Etiqueta de declaración de alérgenos",
    width_mm: 70.0,
    height_mm: 50.0,
    background_color: "#FFFFFF",
    border_width: 0.5,
    border_color: "#CC0000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "alimentacion",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_5_1", type: "text", x: 4.0, y: 3.0, width: 62.0, height: 7.0,
        text_content: "CONTIENE:", binding: nil, font_size: 12.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#CC0000",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_5_2", type: "line", x: 4.0, y: 11.0, width: 62.0, height: 0.4,
        color: "#CC0000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_5_3", type: "text", x: 4.0, y: 14.0, width: 62.0, height: 5.0,
        text_content: nil, binding: "alergeno_1", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Alérgeno 1", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_5_4", type: "text", x: 4.0, y: 21.0, width: 62.0, height: 5.0,
        text_content: nil, binding: "alergeno_2", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Alérgeno 2", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_5_5", type: "text", x: 4.0, y: 28.0, width: 62.0, height: 5.0,
        text_content: nil, binding: "alergeno_3", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Alérgeno 3", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_5_6", type: "text", x: 4.0, y: 37.0, width: 62.0, height: 10.0,
        text_content: nil, binding: "advertencia", font_size: 6.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Advertencia", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 6. Precio/Balanza (60×40mm)
  %{
    name: "Precio balanza",
    description: "Etiqueta de precio para productos a granel o balanza",
    width_mm: 60.0,
    height_mm: 40.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "alimentacion",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_6_1", type: "text", x: 3.0, y: 2.0, width: 54.0, height: 5.0,
        text_content: nil, binding: "nombre", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Nombre", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_2", type: "line", x: 3.0, y: 8.0, width: 54.0, height: 0.3,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_3", type: "text", x: 3.0, y: 10.0, width: 12.0, height: 4.0,
        text_content: "€/kg:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label precio_kg", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_4", type: "text", x: 16.0, y: 10.0, width: 15.0, height: 4.0,
        text_content: nil, binding: "precio_kg", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Precio/kg", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_5", type: "text", x: 33.0, y: 10.0, width: 10.0, height: 4.0,
        text_content: "Peso:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label peso", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_6", type: "text", x: 44.0, y: 10.0, width: 13.0, height: 4.0,
        text_content: nil, binding: "peso", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Peso", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_7", type: "text", x: 3.0, y: 16.0, width: 15.0, height: 5.0,
        text_content: "TOTAL:", binding: nil, font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label total", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_8", type: "text", x: 19.0, y: 15.0, width: 25.0, height: 7.0,
        text_content: nil, binding: "precio_total", font_size: 14.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Precio total", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_6_9", type: "barcode", x: 5.0, y: 24.0, width: 50.0, height: 13.0,
        binding: "ean13", barcode_format: "EAN13", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "EAN-13", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # =================================================================
  # FARMACÉUTICA (5 plantillas)
  # =================================================================

  # 7. Medicamento (80×50mm)
  %{
    name: "Medicamento",
    description: "Etiqueta de medicamento con nombre comercial, principio activo y CN",
    width_mm: 80.0,
    height_mm: 50.0,
    background_color: "#FFFFFF",
    border_width: 0.3,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "farmaceutica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_7_1", type: "text", x: 4.0, y: 3.0, width: 72.0, height: 6.0,
        text_content: nil, binding: "nombre_comercial", font_size: 12.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Nombre comercial", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_2", type: "text", x: 4.0, y: 10.0, width: 72.0, height: 5.0,
        text_content: nil, binding: "principio_activo", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#444444",
        z_index: 10, name: "Principio activo", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_3", type: "line", x: 4.0, y: 16.0, width: 72.0, height: 0.3,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_4", type: "text", x: 4.0, y: 18.0, width: 12.0, height: 4.0,
        text_content: "Dosis:", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label dosis", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_5", type: "text", x: 17.0, y: 18.0, width: 25.0, height: 4.0,
        text_content: nil, binding: "dosis", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Dosis", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_6", type: "text", x: 44.0, y: 18.0, width: 8.0, height: 4.0,
        text_content: "Vía:", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label vía", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_7", type: "text", x: 53.0, y: 18.0, width: 23.0, height: 4.0,
        text_content: nil, binding: "via", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Vía", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_8", type: "text", x: 4.0, y: 24.0, width: 8.0, height: 4.0,
        text_content: "CN:", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label CN", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_9", type: "text", x: 13.0, y: 24.0, width: 30.0, height: 4.0,
        text_content: nil, binding: "codigo_nacional", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Código nacional", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_7_10", type: "barcode", x: 4.0, y: 31.0, width: 72.0, height: 16.0,
        binding: "codigo_nacional", barcode_format: "CODE128", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "Código de barras", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 8. Muestra médica (70×40mm)
  %{
    name: "Muestra médica",
    description: "Etiqueta de muestra médica con aviso de prohibición de venta",
    width_mm: 70.0,
    height_mm: 40.0,
    background_color: "#FFFFFF",
    border_width: 0.5,
    border_color: "#CC0000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "farmaceutica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_8_1", type: "text", x: 4.0, y: 2.0, width: 62.0, height: 5.0,
        text_content: "MUESTRA MÉDICA", binding: nil, font_size: 11.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#CC0000",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_2", type: "text", x: 4.0, y: 7.0, width: 62.0, height: 4.0,
        text_content: "Prohibida su venta", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#CC0000",
        z_index: 10, name: "Aviso", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_3", type: "line", x: 4.0, y: 12.0, width: 62.0, height: 0.4,
        color: "#CC0000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_4", type: "text", x: 4.0, y: 15.0, width: 62.0, height: 5.0,
        text_content: nil, binding: "nombre", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Nombre", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_5", type: "text", x: 4.0, y: 22.0, width: 12.0, height: 4.0,
        text_content: "Lote:", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_6", type: "text", x: 17.0, y: 22.0, width: 18.0, height: 4.0,
        text_content: nil, binding: "lote", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_7", type: "text", x: 38.0, y: 22.0, width: 10.0, height: 4.0,
        text_content: "Cad.:", binding: nil, font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label cad.", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_8", type: "text", x: 49.0, y: 22.0, width: 17.0, height: 4.0,
        text_content: nil, binding: "fecha_caducidad", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Fecha caducidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_8_9", type: "barcode", x: 4.0, y: 28.0, width: 62.0, height: 9.0,
        binding: "lote", barcode_format: "CODE128", barcode_show_text: false, color: "#000000",
        z_index: 8, name: "Código de barras", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 9. Sustancia GHS (100×100mm)
  %{
    name: "Sustancia peligrosa GHS",
    description: "Etiqueta GHS para sustancias peligrosas con pictograma y frases H/P",
    width_mm: 100.0,
    height_mm: 100.0,
    background_color: "#FFFFFF",
    border_width: 0.8,
    border_color: "#CC0000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "farmaceutica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_9_1", type: "text", x: 5.0, y: 4.0, width: 90.0, height: 7.0,
        text_content: nil, binding: "nombre_sustancia", font_size: 12.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Nombre sustancia", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_2", type: "line", x: 5.0, y: 13.0, width: 90.0, height: 0.5,
        color: "#CC0000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_3", type: "rectangle", x: 5.0, y: 16.0, width: 25.0, height: 25.0,
        color: "#CC0000", background_color: "#FFFFFF", border_width: 1.5, border_color: "#CC0000",
        z_index: 6, name: "Marco pictograma", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_4", type: "text", x: 7.0, y: 24.0, width: 21.0, height: 5.0,
        text_content: "PICTOGRAMA", binding: nil, font_size: 6.0, font_weight: "normal",
        font_family: "Arial", text_align: "center", color: "#CC0000",
        z_index: 10, name: "Placeholder picto", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_5", type: "text", x: 35.0, y: 16.0, width: 60.0, height: 8.0,
        text_content: nil, binding: "palabra_señal", font_size: 16.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#CC0000",
        z_index: 10, name: "Palabra señal", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_6", type: "line", x: 5.0, y: 44.0, width: 90.0, height: 0.3,
        color: "#CC0000", z_index: 5, name: "Separador 2", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_7", type: "text", x: 5.0, y: 47.0, width: 90.0, height: 5.0,
        text_content: "Indicaciones de peligro (H):", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label frases H", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_8", type: "text", x: 5.0, y: 53.0, width: 90.0, height: 15.0,
        text_content: nil, binding: "frase_h", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Frases H", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_9", type: "text", x: 5.0, y: 70.0, width: 90.0, height: 5.0,
        text_content: "Consejos de prudencia (P):", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Label frases P", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_9_10", type: "text", x: 5.0, y: 76.0, width: 90.0, height: 20.0,
        text_content: nil, binding: "frase_p", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Frases P", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 10. Laboratorio (50×25mm)
  %{
    name: "Muestra de laboratorio",
    description: "Etiqueta compacta para muestras de laboratorio con QR",
    width_mm: 50.0,
    height_mm: 25.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "farmaceutica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_10_1", type: "text", x: 2.0, y: 2.0, width: 28.0, height: 4.0,
        text_content: nil, binding: "nombre_muestra", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Nombre muestra", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_10_2", type: "text", x: 2.0, y: 7.0, width: 8.0, height: 3.0,
        text_content: "Ref:", binding: nil, font_size: 6.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label ref", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_10_3", type: "text", x: 10.0, y: 7.0, width: 20.0, height: 3.0,
        text_content: nil, binding: "referencia", font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Referencia", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_10_4", type: "text", x: 2.0, y: 11.0, width: 28.0, height: 3.0,
        text_content: nil, binding: "fecha", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#333333",
        z_index: 10, name: "Fecha", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_10_5", type: "qr", x: 33.0, y: 2.0, width: 15.0, height: 15.0,
        binding: "datos_qr", qr_error_level: "M", color: "#000000",
        z_index: 8, name: "QR datos", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 11. Preparado magistral (80×60mm)
  %{
    name: "Fórmula magistral",
    description: "Etiqueta de preparado magistral con composición y posología",
    width_mm: 80.0,
    height_mm: 60.0,
    background_color: "#FFFFFF",
    border_width: 0.3,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "farmaceutica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_11_1", type: "text", x: 4.0, y: 3.0, width: 72.0, height: 5.0,
        text_content: "FÓRMULA MAGISTRAL", binding: nil, font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_2", type: "line", x: 4.0, y: 9.0, width: 72.0, height: 0.3,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_3", type: "text", x: 4.0, y: 11.0, width: 72.0, height: 4.0,
        text_content: "Composición:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#333333",
        z_index: 10, name: "Label composición", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_4", type: "text", x: 4.0, y: 15.0, width: 72.0, height: 8.0,
        text_content: nil, binding: "composicion", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Composición", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_5", type: "text", x: 4.0, y: 24.0, width: 72.0, height: 4.0,
        text_content: "Posología:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#333333",
        z_index: 10, name: "Label posología", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_6", type: "text", x: 4.0, y: 28.0, width: 72.0, height: 6.0,
        text_content: nil, binding: "posologia", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Posología", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_7", type: "line", x: 4.0, y: 35.0, width: 72.0, height: 0.2,
        color: "#CCCCCC", z_index: 5, name: "Separador 2", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_8", type: "text", x: 4.0, y: 37.0, width: 18.0, height: 4.0,
        text_content: "Paciente:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#333333",
        z_index: 10, name: "Label paciente", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_9", type: "text", x: 23.0, y: 37.0, width: 53.0, height: 4.0,
        text_content: nil, binding: "paciente", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Paciente", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_10", type: "text", x: 4.0, y: 42.0, width: 18.0, height: 4.0,
        text_content: "Farmacia:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#333333",
        z_index: 10, name: "Label farmacia", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_11", type: "text", x: 23.0, y: 42.0, width: 53.0, height: 4.0,
        text_content: nil, binding: "farmacia", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Farmacia", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_12", type: "text", x: 4.0, y: 48.0, width: 14.0, height: 4.0,
        text_content: "Fecha:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label fecha", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_11_13", type: "text", x: 19.0, y: 48.0, width: 25.0, height: 4.0,
        text_content: nil, binding: "fecha", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Fecha", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # =================================================================
  # LOGÍSTICA (5 plantillas)
  # =================================================================

  # 12. Envío (100×150mm)
  %{
    name: "Etiqueta de envío",
    description: "Etiqueta de envío con remitente, destinatario, tracking y QR",
    width_mm: 100.0,
    height_mm: 150.0,
    background_color: "#FFFFFF",
    border_width: 0.3,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "logistica",
    label_type: "multiple",
    elements: [
      # Remitente
      %{id: "el_tpl_12_1", type: "text", x: 5.0, y: 4.0, width: 90.0, height: 4.0,
        text_content: "REMITENTE", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#888888",
        z_index: 10, name: "Label remitente", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_2", type: "text", x: 5.0, y: 9.0, width: 90.0, height: 5.0,
        text_content: nil, binding: "remitente", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Remitente", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_3", type: "line", x: 5.0, y: 18.0, width: 90.0, height: 0.8,
        color: "#000000", z_index: 5, name: "Separador grueso", visible: true, locked: false, rotation: 0.0},
      # Destinatario
      %{id: "el_tpl_12_4", type: "text", x: 5.0, y: 22.0, width: 90.0, height: 5.0,
        text_content: "DESTINATARIO", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label destinatario", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_5", type: "text", x: 5.0, y: 29.0, width: 90.0, height: 7.0,
        text_content: nil, binding: "destinatario", font_size: 12.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Destinatario", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_6", type: "text", x: 5.0, y: 38.0, width: 90.0, height: 6.0,
        text_content: nil, binding: "direccion", font_size: 10.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Dirección", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_7", type: "text", x: 5.0, y: 46.0, width: 20.0, height: 6.0,
        text_content: nil, binding: "cp", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Código postal", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_8", type: "text", x: 27.0, y: 46.0, width: 68.0, height: 6.0,
        text_content: nil, binding: "ciudad", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Ciudad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_9", type: "line", x: 5.0, y: 56.0, width: 90.0, height: 0.3,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      # Tracking + QR
      %{id: "el_tpl_12_10", type: "barcode", x: 5.0, y: 60.0, width: 90.0, height: 35.0,
        binding: "tracking", barcode_format: "CODE128", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "Código tracking", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_11", type: "qr", x: 5.0, y: 100.0, width: 40.0, height: 40.0,
        binding: "tracking", qr_error_level: "M", color: "#000000",
        z_index: 8, name: "QR tracking", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_12", type: "text", x: 50.0, y: 110.0, width: 45.0, height: 5.0,
        text_content: "Tracking:", binding: nil, font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#888888",
        z_index: 10, name: "Label tracking", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_12_13", type: "text", x: 50.0, y: 116.0, width: 45.0, height: 5.0,
        text_content: nil, binding: "tracking", font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Nº tracking", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 13. Pallet (105×148mm)
  %{
    name: "Etiqueta de pallet",
    description: "Etiqueta estándar de pallet con SSCC, origen, destino y peso",
    width_mm: 105.0,
    height_mm: 148.0,
    background_color: "#FFFFFF",
    border_width: 0.3,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "logistica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_13_1", type: "text", x: 5.0, y: 4.0, width: 95.0, height: 6.0,
        text_content: "ETIQUETA DE PALLET", binding: nil, font_size: 11.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_2", type: "line", x: 5.0, y: 12.0, width: 95.0, height: 0.5,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_3", type: "text", x: 5.0, y: 16.0, width: 15.0, height: 5.0,
        text_content: "SSCC:", binding: nil, font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label SSCC", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_4", type: "text", x: 22.0, y: 15.0, width: 78.0, height: 7.0,
        text_content: nil, binding: "sscc", font_size: 12.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "SSCC", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_5", type: "line", x: 5.0, y: 25.0, width: 95.0, height: 0.3,
        color: "#CCCCCC", z_index: 5, name: "Línea", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_6", type: "text", x: 5.0, y: 28.0, width: 18.0, height: 4.0,
        text_content: "Origen:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label origen", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_7", type: "text", x: 24.0, y: 28.0, width: 76.0, height: 4.0,
        text_content: nil, binding: "origen", font_size: 9.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Origen", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_8", type: "text", x: 5.0, y: 35.0, width: 18.0, height: 4.0,
        text_content: "Destino:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label destino", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_9", type: "text", x: 24.0, y: 35.0, width: 76.0, height: 4.0,
        text_content: nil, binding: "destino", font_size: 9.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Destino", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_10", type: "text", x: 5.0, y: 42.0, width: 22.0, height: 4.0,
        text_content: "Contenido:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label contenido", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_11", type: "text", x: 28.0, y: 42.0, width: 72.0, height: 4.0,
        text_content: nil, binding: "contenido", font_size: 9.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Contenido", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_12", type: "text", x: 5.0, y: 49.0, width: 24.0, height: 4.0,
        text_content: "Peso bruto:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label peso", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_13", type: "text", x: 30.0, y: 49.0, width: 30.0, height: 4.0,
        text_content: nil, binding: "peso_bruto", font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Peso bruto", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_14", type: "line", x: 5.0, y: 56.0, width: 95.0, height: 0.5,
        color: "#000000", z_index: 5, name: "Separador 2", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_13_15", type: "barcode", x: 5.0, y: 60.0, width: 95.0, height: 80.0,
        binding: "sscc", barcode_format: "CODE128", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "Código SSCC", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 14. Ubicación de almacén (60×30mm)
  %{
    name: "Ubicación de almacén",
    description: "Etiqueta de ubicación para estanterías de almacén",
    width_mm: 60.0,
    height_mm: 30.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "logistica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_14_1", type: "text", x: 2.0, y: 1.0, width: 56.0, height: 4.0,
        text_content: "UBICACIÓN", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#888888",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_14_2", type: "text", x: 2.0, y: 5.0, width: 56.0, height: 9.0,
        text_content: nil, binding: "codigo_ubicacion", font_size: 16.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Código ubicación", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_14_3", type: "barcode", x: 3.0, y: 16.0, width: 54.0, height: 12.0,
        binding: "codigo_ubicacion", barcode_format: "CODE128", barcode_show_text: false, color: "#000000",
        z_index: 8, name: "Código de barras", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 15. Devolución (100×70mm)
  %{
    name: "Etiqueta de devolución",
    description: "Etiqueta de autorización de devolución con motivo y QR",
    width_mm: 100.0,
    height_mm: 70.0,
    background_color: "#FFFFFF",
    border_width: 0.5,
    border_color: "#E67E22",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "logistica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_15_1", type: "text", x: 5.0, y: 4.0, width: 90.0, height: 10.0,
        text_content: "DEVOLUCIÓN", binding: nil, font_size: 18.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#E67E22",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_2", type: "line", x: 5.0, y: 16.0, width: 90.0, height: 0.5,
        color: "#E67E22", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_3", type: "text", x: 5.0, y: 19.0, width: 35.0, height: 4.0,
        text_content: "Nº Autorización:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label autorización", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_4", type: "text", x: 42.0, y: 19.0, width: 30.0, height: 5.0,
        text_content: nil, binding: "num_autorizacion", font_size: 11.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Nº autorización", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_5", type: "text", x: 5.0, y: 27.0, width: 15.0, height: 4.0,
        text_content: "Motivo:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label motivo", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_6", type: "text", x: 22.0, y: 27.0, width: 50.0, height: 4.0,
        text_content: nil, binding: "motivo", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Motivo", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_7", type: "text", x: 5.0, y: 34.0, width: 65.0, height: 4.0,
        text_content: "Dirección de retorno:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label retorno", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_8", type: "text", x: 5.0, y: 39.0, width: 65.0, height: 8.0,
        text_content: nil, binding: "direccion_retorno", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Dirección retorno", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_15_9", type: "qr", x: 73.0, y: 19.0, width: 22.0, height: 22.0,
        binding: "num_autorizacion", qr_error_level: "M", color: "#000000",
        z_index: 8, name: "QR autorización", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 16. Contenido de caja (80×50mm)
  %{
    name: "Contenido de caja",
    description: "Etiqueta con detalle de contenido, cantidad y peso",
    width_mm: 80.0,
    height_mm: 50.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "logistica",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_16_1", type: "text", x: 4.0, y: 2.0, width: 72.0, height: 5.0,
        text_content: "CONTENIDO", binding: nil, font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_2", type: "line", x: 4.0, y: 8.0, width: 72.0, height: 0.3,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_3", type: "text", x: 4.0, y: 10.0, width: 8.0, height: 4.0,
        text_content: "Ref:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label ref", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_4", type: "text", x: 13.0, y: 10.0, width: 30.0, height: 4.0,
        text_content: nil, binding: "referencia", font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Referencia", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_5", type: "text", x: 4.0, y: 16.0, width: 72.0, height: 4.0,
        text_content: nil, binding: "descripcion", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Descripción", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_6", type: "text", x: 4.0, y: 22.0, width: 18.0, height: 4.0,
        text_content: "Cantidad:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label cantidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_7", type: "text", x: 23.0, y: 22.0, width: 15.0, height: 4.0,
        text_content: nil, binding: "cantidad", font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Cantidad", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_8", type: "text", x: 42.0, y: 22.0, width: 12.0, height: 4.0,
        text_content: "Peso:", binding: nil, font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label peso", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_9", type: "text", x: 55.0, y: 22.0, width: 21.0, height: 4.0,
        text_content: nil, binding: "peso", font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Peso", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_16_10", type: "barcode", x: 4.0, y: 29.0, width: 72.0, height: 18.0,
        binding: "referencia", barcode_format: "CODE128", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "Código de barras", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # =================================================================
  # MANUFACTURA (4 plantillas)
  # =================================================================

  # 17. Pieza/Componente (50×25mm)
  %{
    name: "Pieza / Componente",
    description: "Etiqueta compacta de identificación de pieza con CODE39",
    width_mm: 50.0,
    height_mm: 25.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "manufactura",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_17_1", type: "text", x: 2.0, y: 1.0, width: 46.0, height: 5.0,
        text_content: nil, binding: "num_pieza", font_size: 10.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Nº pieza", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_17_2", type: "text", x: 2.0, y: 6.0, width: 36.0, height: 3.0,
        text_content: nil, binding: "descripcion", font_size: 6.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Descripción", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_17_3", type: "text", x: 38.0, y: 6.0, width: 10.0, height: 3.0,
        text_content: nil, binding: "revision", font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "right", color: "#888888",
        z_index: 10, name: "Revisión", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_17_4", type: "barcode", x: 2.0, y: 11.0, width: 46.0, height: 12.0,
        binding: "num_pieza", barcode_format: "CODE39", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "CODE39", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 18. Activo fijo (40×20mm)
  %{
    name: "Activo fijo",
    description: "Etiqueta de inventario de activos con QR",
    width_mm: 40.0,
    height_mm: 20.0,
    background_color: "#FFFFFF",
    border_width: 0.2,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "manufactura",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_18_1", type: "text", x: 2.0, y: 1.0, width: 10.0, height: 3.0,
        text_content: "ACTIVO", binding: nil, font_size: 5.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#888888",
        z_index: 10, name: "Label activo", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_18_2", type: "text", x: 2.0, y: 4.0, width: 20.0, height: 5.0,
        text_content: nil, binding: "num_activo", font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Nº activo", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_18_3", type: "text", x: 2.0, y: 10.0, width: 20.0, height: 3.0,
        text_content: nil, binding: "descripcion", font_size: 5.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Descripción", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_18_4", type: "text", x: 2.0, y: 14.0, width: 20.0, height: 3.0,
        text_content: nil, binding: "departamento", font_size: 5.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#888888",
        z_index: 10, name: "Departamento", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_18_5", type: "qr", x: 24.0, y: 2.0, width: 14.0, height: 14.0,
        binding: "num_activo", qr_error_level: "M", color: "#000000",
        z_index: 8, name: "QR inventario", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 19. Inspección QC (60×40mm)
  %{
    name: "Inspección QC",
    description: "Etiqueta de control de calidad con estado de aprobación",
    width_mm: 60.0,
    height_mm: 40.0,
    background_color: "#FFFFFF",
    border_width: 0.4,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "manufactura",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_19_1", type: "text", x: 3.0, y: 2.0, width: 54.0, height: 9.0,
        text_content: nil, binding: "estado", font_size: 16.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Estado", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_2", type: "line", x: 3.0, y: 12.0, width: 54.0, height: 0.4,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_3", type: "text", x: 3.0, y: 15.0, width: 18.0, height: 4.0,
        text_content: "Inspector:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label inspector", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_4", type: "text", x: 22.0, y: 15.0, width: 35.0, height: 4.0,
        text_content: nil, binding: "inspector", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Inspector", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_5", type: "text", x: 3.0, y: 21.0, width: 14.0, height: 4.0,
        text_content: "Fecha:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label fecha", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_6", type: "text", x: 18.0, y: 21.0, width: 20.0, height: 4.0,
        text_content: nil, binding: "fecha", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Fecha", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_7", type: "text", x: 3.0, y: 27.0, width: 12.0, height: 4.0,
        text_content: "Lote:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_8", type: "text", x: 16.0, y: 27.0, width: 25.0, height: 4.0,
        text_content: nil, binding: "lote", font_size: 8.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_19_9", type: "barcode", x: 3.0, y: 33.0, width: 54.0, height: 5.0,
        binding: "lote", barcode_format: "CODE128", barcode_show_text: false, color: "#000000",
        z_index: 8, name: "Código de barras", visible: true, locked: false, rotation: 0.0}
    ]
  },

  # 20. Lote de producción (80×50mm)
  %{
    name: "Lote de producción",
    description: "Etiqueta de lote con producto, fechas, turno y máquina",
    width_mm: 80.0,
    height_mm: 50.0,
    background_color: "#FFFFFF",
    border_width: 0.3,
    border_color: "#000000",
    border_radius: 0.0,
    is_template: true,
    template_source: "system",
    template_category: "manufactura",
    label_type: "multiple",
    elements: [
      %{id: "el_tpl_20_1", type: "text", x: 4.0, y: 2.0, width: 72.0, height: 5.0,
        text_content: "LOTE DE PRODUCCIÓN", binding: nil, font_size: 9.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#555555",
        z_index: 10, name: "Título", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_2", type: "text", x: 4.0, y: 7.0, width: 72.0, height: 6.0,
        text_content: nil, binding: "num_lote", font_size: 12.0, font_weight: "bold",
        font_family: "Arial", text_align: "center", color: "#000000",
        z_index: 10, name: "Nº lote", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_3", type: "line", x: 4.0, y: 14.0, width: 72.0, height: 0.3,
        color: "#000000", z_index: 5, name: "Separador", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_4", type: "text", x: 4.0, y: 16.0, width: 72.0, height: 4.0,
        text_content: nil, binding: "producto", font_size: 8.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Producto", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_5", type: "text", x: 4.0, y: 22.0, width: 14.0, height: 4.0,
        text_content: "Inicio:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label inicio", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_6", type: "text", x: 19.0, y: 22.0, width: 18.0, height: 4.0,
        text_content: nil, binding: "fecha_inicio", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Fecha inicio", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_7", type: "text", x: 40.0, y: 22.0, width: 8.0, height: 4.0,
        text_content: "Fin:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label fin", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_8", type: "text", x: 49.0, y: 22.0, width: 18.0, height: 4.0,
        text_content: nil, binding: "fecha_fin", font_size: 7.0, font_weight: "normal",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Fecha fin", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_9", type: "text", x: 4.0, y: 28.0, width: 12.0, height: 4.0,
        text_content: "Turno:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label turno", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_10", type: "text", x: 17.0, y: 28.0, width: 15.0, height: 4.0,
        text_content: nil, binding: "turno", font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Turno", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_11", type: "text", x: 35.0, y: 28.0, width: 18.0, height: 4.0,
        text_content: "Máquina:", binding: nil, font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#555555",
        z_index: 10, name: "Label máquina", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_12", type: "text", x: 54.0, y: 28.0, width: 22.0, height: 4.0,
        text_content: nil, binding: "maquina", font_size: 7.0, font_weight: "bold",
        font_family: "Arial", text_align: "left", color: "#000000",
        z_index: 10, name: "Máquina", visible: true, locked: false, rotation: 0.0},
      %{id: "el_tpl_20_13", type: "barcode", x: 4.0, y: 34.0, width: 72.0, height: 13.0,
        binding: "num_lote", barcode_format: "CODE128", barcode_show_text: true, color: "#000000",
        z_index: 8, name: "Código de barras", visible: true, locked: false, rotation: 0.0}
    ]
  }
]

# Insert all templates
Enum.each(templates, fn template_data ->
  %Design{}
  |> Design.changeset(template_data)
  |> Repo.insert!()
end)

IO.puts("Inserted #{length(templates)} system templates.")
